### PR TITLE
fix: Improve SEO component

### LINKED ISSUE #41: Beef up our SEO component
We're going to want OG tags and all that nonsense, and check to be sure everything's working as it should.

https://www.gatsbyjs.org/docs/add-seo-component/
https://www.gatsbyjs.org/docs/add-page-metadata/

https://www.redclayinteractive.com/what-are-open-graph-tags/

### PR DESCRIPTION
**Pull request by sarahmonster**
Fixes #41 when merged. 

Before: 
https://opengraphcheck.com/result.php?url=https%3A%2F%2Foctopusthink.com%2Fblog%2F2020-01-13-2019-year-in-review

After: Probably better!

Here's what's left on my to-do list:

- [x] add images (in progress & stashed locally...need help with where to store & how to access images)
- [x] make default image
- [ ] add images for all/any posts & pages as needed
- [x] test twitter
- [x] test facebook
- [ ] ~~consider using new blogUrl config value elsewhere~~

Questions I have:

- Right now, the site author (@octopusthinks) is listed as the author (on Twitter cards) for all posts, pages, etc. We can get a bit more granular, though.... so we could maybe go more specific with individual posts & pages, using authors.yaml data, and then either replace the `twitter:creator` tag and/or use `article:author` (which takes an array of profiles, so we'd need to build that out too). I suspect this might be complex enough to warrant a secondary PR, but worth thinking now about how we want to handle authorship in tags (and how we want it to work for Ghost Ship, where there may be a more compelling reason to get more specific about authorship.)
- Right now, language is set using a default prop, which is fine here but not great for Ghost Ship. Ideally, we could pass the siteconfig language value to the SEO component, using it as the default value, but allowing individual pages to overwrite if they need to. (Actually, I may be able to handle this myself. In progress; see 58f6894.)
- Do we need to consider keywords anywhere? Right now I haven't bothered, and I'm not convinced it's important enough to bother.
- Is there anything else we should add/embellish/improve?

### CODE REVIEW

File: gatsby-node.js [hunk 1]
```diff
@@ -102,7 +102,7 @@ const makeBlogTags = ({ actions, tags }) => {
   const { createPage } = actions;
 
   tags.forEach((tag) => {
-    const slug = `/blog/tags/${tag.id}/`;
+    const slug = `/blog/tag/${tag.id}/`;
```
Comment (tofumatt) [inline gatsby-node.js]: We shouldn't change these, because the URLs are already live. Cool URLs don't change, so we may want to live with this. is it gonna be that bad? Also plurals here I feel are normal/easier to deal with when typing (eg removing the tag—`/blog/tags/travel` --> `/blog/tags` is more natural when manually experimenting with URLs rather than `/blog/tag/travel` --> `/blog/tags`).

File: src/components/SEO/index.js [hunk 2]
```diff
@@ -64,21 +130,26 @@ function SEO(props) {
...
-      <title>{pageTitle}</title>
+      <title>{pageDisplayTitle}</title>
+      <link rel="canonical" href={seo.url} />
     </Helmet>
   );
 }
 
 SEO.defaultProps = {
-  lang: `en-GB`,
+  lang: undefined,
```
Comment (tofumatt) [inline src/components/SEO/index.js]: Should this be undefined? Don't we have a site language set somewhere?

File: src/content/blog/2019-11-22-ethics-at-the-heart-of-business.mdx [hunk 3]
```diff
@@ -3,7 +3,8 @@ authors: [sarah]
 tags: [ethics]
 title: Making ethics the beating heart(s) of our business
 summary: Saying you're all about ethics is one thing, but actually quantifying it and holding yourself accountable is another thing entirely. Let's get specific about what "ethical business practices" actually means.
-updated: 2019-11-22
+thumbnail: '/og-images/blog/2019-11-22-ethics-at-the-heart-of-business.png'
+updated: 2020-02-02
```
Comment (tofumatt) [inline src/content/blog/2019-11-22-ethics-at-the-heart-of-business.mdx]: That's… not _really_ true. I feel like this implies the content or something was updated, but in this case we're adding a feature to the site. That image is already on the page, so it's not really an update…

File: src/templates/Blog/Post.js [hunk 4]
```diff
@@ -65,7 +76,7 @@ export const BlogPost = (props) => {
               return (
                 <Tags.Tag>
                   <Link
-                    to={`/blog/tags/${tag.id}`}
+                    to={`/blog/tag/${tag.id}`}
```
Comment (tofumatt) [inline src/templates/Blog/Post.js]: Again: I don't think we should change this.

File: src/templates/Blog/Tag.js [hunk 5]
```diff
@@ -15,23 +16,28 @@ export const BlogTags = (props) => {
 
   let pageSummary;
   let pageTitle;
+  let pageSlug;
+
   if (tag.edges.length > 0) {
     const tagData = tag.edges[0].node;
     pageTitle = `Posts tagged #${tagData.name}`;
     pageSummary = tagData.summary;
+    pageSlug = `${config.blogUrl}tag/${tagData.name}`;
```
Comment (tofumatt) [inline src/templates/Blog/Tag.js]:
```suggestion
    pageSlug = `${config.blogUrl}tags/${tagData.name}`;
```

File: src/templates/Blog/Tag.js [hunk 6]
```diff
@@ -15,23 +16,28 @@ export const BlogTags = (props) => {
...
   } else {
     pageTitle = `Posts tagged #${pageContext.tag}`;
     pageSummary = `An archive of blog posts tagged #${pageContext.tag}`;
+    pageSlug = `${config.blogUrl}tag/${pageContext.tag}`;
```
Comment (tofumatt) [inline src/templates/Blog/Tag.js]:
```suggestion
    pageSlug = `${config.blogUrl}tags/${pageContext.tag}`;
```

File: src/components/SEO/index.js (hunk 2 above)
Comment (tofumatt) [reply src/components/SEO/index.js]: Confusingly, this means it actually uses the `siteConfig` fallback. Maybe we ought to document that:
```suggestion
  // If this prop is `undefined`, `siteConfig.language` will be used as a fallback.
  lang: undefined,
```
